# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
import numpy as np

#### 2. Print your NumPy version.

In [7]:
print(np.__version__)

1.22.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
a = np.random.random((2,3,5))
print(a)

[[[0.72708245 0.71199436 0.60373158 0.38691948 0.54303985]
  [0.35222244 0.86801516 0.4760973  0.11946089 0.71893863]
  [0.18198273 0.88959695 0.64787349 0.52438062 0.85636445]]

 [[0.78957323 0.64680252 0.26042885 0.45966897 0.874562  ]
  [0.45549488 0.11891136 0.23782735 0.63863821 0.14196462]
  [0.20004679 0.80266081 0.70515997 0.65861492 0.3704515 ]]]


In [9]:
copy_a = a.copy()
print(copy_a)

[[[0.72708245 0.71199436 0.60373158 0.38691948 0.54303985]
  [0.35222244 0.86801516 0.4760973  0.11946089 0.71893863]
  [0.18198273 0.88959695 0.64787349 0.52438062 0.85636445]]

 [[0.78957323 0.64680252 0.26042885 0.45966897 0.874562  ]
  [0.45549488 0.11891136 0.23782735 0.63863821 0.14196462]
  [0.20004679 0.80266081 0.70515997 0.65861492 0.3704515 ]]]


In [10]:
a1 = np.empty((2,3,5))
a1

array([[[0.72708245, 0.71199436, 0.60373158, 0.38691948, 0.54303985],
        [0.35222244, 0.86801516, 0.4760973 , 0.11946089, 0.71893863],
        [0.18198273, 0.88959695, 0.64787349, 0.52438062, 0.85636445]],

       [[0.78957323, 0.64680252, 0.26042885, 0.45966897, 0.874562  ],
        [0.45549488, 0.11891136, 0.23782735, 0.63863821, 0.14196462],
        [0.20004679, 0.80266081, 0.70515997, 0.65861492, 0.3704515 ]]])

#### 4. Print *a*.


In [11]:
print(a)

[[[0.72708245 0.71199436 0.60373158 0.38691948 0.54303985]
  [0.35222244 0.86801516 0.4760973  0.11946089 0.71893863]
  [0.18198273 0.88959695 0.64787349 0.52438062 0.85636445]]

 [[0.78957323 0.64680252 0.26042885 0.45966897 0.874562  ]
  [0.45549488 0.11891136 0.23782735 0.63863821 0.14196462]
  [0.20004679 0.80266081 0.70515997 0.65861492 0.3704515 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [13]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
print(a.size) 
print(b.size) 

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [15]:
print(np.add(a, b))  # no se puede sumar al no tener la misma forma

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
d = np.add(a,c)
d
#they have the sime shape
print(d.shape)

(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
print(a) #we have sum 1.0 to every value.

[[[0.96721469 0.8871614  0.36551847 0.82635097 0.2236851 ]
  [0.64621289 0.713039   0.67146643 0.65632011 0.25249168]
  [0.52313032 0.03876759 0.69055098 0.13061931 0.92356728]]

 [[0.54192418 0.5059538  0.80835549 0.56554107 0.2678267 ]
  [0.18420083 0.74500435 0.11550593 0.90586616 0.82886038]
  [0.56092419 0.99172108 0.7755791  0.39907362 0.73724568]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
e = np.multiply(a, c)
e

array([[[0.72708245, 0.71199436, 0.60373158, 0.38691948, 0.54303985],
        [0.35222244, 0.86801516, 0.4760973 , 0.11946089, 0.71893863],
        [0.18198273, 0.88959695, 0.64787349, 0.52438062, 0.85636445]],

       [[0.78957323, 0.64680252, 0.26042885, 0.45966897, 0.874562  ],
        [0.45549488, 0.11891136, 0.23782735, 0.63863821, 0.14196462],
        [0.20004679, 0.80266081, 0.70515997, 0.65861492, 0.3704515 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
# sí, a = e porque hemos multiplicado por 1

array([[[0.96721469, 0.8871614 , 0.36551847, 0.82635097, 0.2236851 ],
        [0.64621289, 0.713039  , 0.67146643, 0.65632011, 0.25249168],
        [0.52313032, 0.03876759, 0.69055098, 0.13061931, 0.92356728]],

       [[0.54192418, 0.5059538 , 0.80835549, 0.56554107, 0.2678267 ],
        [0.18420083, 0.74500435, 0.11550593, 0.90586616, 0.82886038],
        [0.56092419, 0.99172108, 0.7755791 , 0.39907362, 0.73724568]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_min)
print(d_max)
print(d_mean)

1.1189113612510648
1.8895969470859302
1.5322835457894042


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
f = np.empty((2,3,5))
f
print(f)

[[[1.72708245 1.71199436 1.60373158 1.38691948 1.54303985]
  [1.35222244 1.86801516 1.4760973  1.11946089 1.71893863]
  [1.18198273 1.88959695 1.64787349 1.52438062 1.85636445]]

 [[1.78957323 1.64680252 1.26042885 1.45966897 1.874562  ]
  [1.45549488 1.11891136 1.23782735 1.63863821 1.14196462]
  [1.20004679 1.80266081 1.70515997 1.65861492 1.3704515 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [99]:
f1 = [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]


In [ ]:
#solución encontrada online, empecé los loops sin saber colocar el resultado, ver abajo

In [102]:
for i in d:
    for j in i:
        for g in j: 
            if d_min<g<d_mean:
                print(25)
            if d_mean<g< d_max:
                print(75)
            if g == d_mean:
                print(50)
            if g == d_min:
                print (0)
            if g == d_max:
                print(100)
                

75
75
75
25
75
25
75
25
25
75
25
100
75
25
75
75
75
25
25
75
25
0
25
75
25
25
75
75
75
25


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [100]:
print(d)
print(f1)

[[[1.72708245 1.71199436 1.60373158 1.38691948 1.54303985]
  [1.35222244 1.86801516 1.4760973  1.11946089 1.71893863]
  [1.18198273 1.88959695 1.64787349 1.52438062 1.85636445]]

 [[1.78957323 1.64680252 1.26042885 1.45966897 1.874562  ]
  [1.45549488 1.11891136 1.23782735 1.63863821 1.14196462]
  [1.20004679 1.80266081 1.70515997 1.65861492 1.3704515 ]]]
[[[75, 75, 75, 25, 75], [25, 75, 25, 25, 75], [25, 100, 75, 25, 75]], [[75, 75, 25, 25, 75], [25, 0, 25, 75, 25], [25, 75, 75, 75, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here